# Exemple d'application NGINX pour tests
# Usage: kubectl apply -f kubernetes/examples/nginx-demo.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: lab-k8s
  labels:
    app: nginx-demo
    purpose: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: nginx-demo-html

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo-html
  namespace: lab-k8s
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Infomaniak K8s Lab</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
            }
            .container {
                text-align: center;
                padding: 2rem;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 10px;
                backdrop-filter: blur(10px);
            }
            h1 { font-size: 3rem; margin: 0; }
            p { font-size: 1.2rem; }
            .info { margin-top: 2rem; font-size: 0.9rem; opacity: 0.8; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Infomaniak Kubernetes Lab</h1>
            <p>Application NGINX de démonstration</p>
            <div class="info">
                <p>Namespace: lab-k8s</p>
                <p>Pod: <span id="hostname">...</span></p>
            </div>
        </div>
        <script>
            fetch('/hostname').catch(() => {
                document.getElementById('hostname').textContent = window.location.hostname;
            });
        </script>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: lab-k8s
  labels:
    app: nginx-demo
spec:
  type: ClusterIP
  selector:
    app: nginx-demo
  ports:
  - port: 80
    targetPort: 80
    name: http

---
# HorizontalPodAutoscaler pour démonstration autoscaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-demo-hpa
  namespace: lab-k8s
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-demo
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
