name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck jq curl unzip nodejs npm
          # kubeval
          curl -sL -o /usr/local/bin/kubeval \
            https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64
          sudo chmod +x /usr/local/bin/kubeval
          # markdownlint
          sudo npm install -g markdownlint-cli

      - name: Shellcheck (scripts/)
        if: ${{ always() }}
        run: |
          if [ -d scripts ]; then
            find scripts -type f -name '*.sh' -print0 | xargs -0 -r shellcheck -x
          fi

      - name: Markdown lint
        run: |
          markdownlint '**/*.md' || true

      - name: Terraform fmt check
        if: ${{ always() }}
        working-directory: ./terraform
        run: |
          if [ -d terraform ]; then
            terraform init -backend=false
            terraform fmt -check
          fi

      - name: Terraform validate
        if: ${{ always() }}
        working-directory: ./terraform
        run: |
          if [ -d terraform ]; then
            terraform init -backend=false
            terraform validate || true
          fi

      - name: Kube manifests validation (kubeval)
        if: ${{ always() }}
        run: |
          if [ -d kubernetes ]; then
            find kubernetes -type f \( -name '*.yml' -o -name '*.yaml' \) -print0 | xargs -0 -r kubeval || true
          fi
